---
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: mysqldb-pvc
  namespace: myns
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: dobs.csi.digitalocean.com

spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # kubectl.exe get storageclasses.storage.k8s.io
  storageClassName: do-block-storage
