---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nwapp-deploy
  namespace: mynwns
  labels:
    app.kubernetes.io/name: nwapp-deploy
    app.kubernetes.io/version: v1
    app.kubernetes.io/component: application
spec:
  replicas: 3
  selector:
    matchLabels:
      name: nwapp-pod
      version: v1
  template:
    metadata:
      name: nwapp-pod
      labels:
        name: nwapp-pod
        version: v1
    spec:
      containers:
      - name: nwapp
        image: twee1990/mynorthwindapp:v0.0.2
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: nwapp-secret
              key: db_password
        - name: DB_HOST
          valueFrom: 
            configMapKeyRef:
              name: nwapp-config
              key: db_host
        - name: DB_USER
          valueFrom: 
            configMapKeyRef:
              name: nwapp-config
              key: db_user
        - name: INSTANCE_IP_ADDRESS
          valueFrom:
            fieldRef: 
              apiVersion: v1
              fieldPath: status.hostIP
        ports:
        - name: nwapp-port
          containerPort: 3000
---
apiVersion: v1
kind: Service

metadata:
  name: nwapp-svc
  namespace: mynwns
  labels:
    name: nwapp-svc
    version: v1

spec:
  type: LoadBalancer
  selector:
    name: nwapp-pod
    version: v1
  ports:
  - name: http
    port: 80
    targetPort: nwapp-port
    protocol: TCP