---
apiVersion: v1
kind: Namespace
metadata:
  name: mynwns
  labels:
    version: v1
---
apiVersion: v1
kind: ConfigMap

metadata:
  name: nwapp-config
  namespace: mynwns

data:
  db_user: root
  db_host: nwdb-svc.mynwns.svc.cluster.local
---
apiVersion: v1
kind: Secret

metadata:
  name: nwapp-secret
  namespace: mynwns

data:
  db_password: bXlud3Bhc3M=