---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nwdb-deploy
  namespace: mynwns
  labels:
    app.kubernetes.io/name: nwdb-deploy
    app.kubernetes.io/version: v1
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: nwapp-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nwdb-pod
      version: v1
  template:
    metadata:
      name: nwdb-pod
      labels:
        name: nwdb-pod
        version: v1
    spec:
      containers:
      - name: nwdb-container
        image: twee1990/mynorthwinddb:v0.0.2
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: nwapp-secret
              key: db_password
        ports:
        - name: mysql
          containerPort: 3306
---
apiVersion: v1
kind: Service

metadata:
  name: nwdb-svc
  namespace: mynwns
  labels:
    name: nwdb-svc
    version: v1

spec:
  type: ClusterIP
  selector:
    name: nwdb-pod
    version: v1
  ports:
  - name: nwdb-port
    port: 3306
    targetPort: mysql
    protocol: TCP